apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy24
  labels:
    app: autodeploy24
  namespace: namespace-workflow-1695625472346
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy24
  template:
    metadata:
      labels:
        app: autodeploy24
    spec:
      containers:
        - name: autodeploy24
          image: acrworkflow1695625472346.azurecr.io/image-workflow-1695625472346:latest
          ports:
            - containerPort: 5000